#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Action {
  Quit,
  Resume,
  Suspend,
  Tick,
  RenderTick,
  Resize(u16, u16),
  ToggleShowLogger,
  ScheduleIncrement,
  ScheduleDecrement,
  Increment(usize),
  Decrement(usize),
  EnterNormal,
  EnterSearch,
  EnterProcessing,
  ExitProcessing,
  SetLogs(String),
  Update,
  Noop,
}
